[package]
name = "clipboard-history-wayland"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Wayland Ringboard clipboard listener."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "wayland"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
arrayvec = "0.7.6"
env_logger = { version = "0.11.6", default-features = false }
error-stack = { version = "0.5.0", default-features = false, features = ["std"] }
log = { version = "0.4.22", features = ["release_max_level_info"] }
ringboard-sdk = { package = "clipboard-history-client-sdk", version = "0", path = "../client-sdk", features = ["error-stack", "config"] }
ringboard-watcher-utils = { package = "clipboard-history-watcher-utils", version = "0", path = "../watcher-utils" }
rustc-hash = "2.1.0"
rustix = { version = "0.38.42", features = ["pipe", "event"] }
thiserror = "2.0.9"
wayland-client = "0.31.7"
wayland-protocols = { version = "0.32.5", features = ["client", "staging"] }
wayland-protocols-misc = { version = "0.3.5", features = ["client"] }
wayland-protocols-wlr = { version = "0.3.5", features = ["client"] }

[features]
default = ["human-logs"]
human-logs = ["env_logger/default"]

[[bin]]
name = "ringboard-wayland"
path = "src/main.rs"
