[package]
name = "clipboard-history-tui"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Ringboard ratatui client application."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "ratatui"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
error-stack = { version = "0.5.0", default-features = false, features = ["std"] }
ratatui = "0.27.0"
regex = "1.10.5"
ringboard-sdk = { package = "clipboard-history-client-sdk", version = "0", path = "../client-sdk" }
thiserror = "1.0.63"

[[bin]]
name = "ringboard-tui"
path = "src/main.rs"
