[package]
name = "clipboard-history-tui"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Ringboard ratatui client application."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "ratatui"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
error-stack = { version = "0.5.0", default-features = false, features = ["std"] }
ratatui = "0.28.1"
ratatui-image = { version = "1.0.5", features = ["crossterm"] }
regex = "1.10.6"
ringboard-sdk = { package = "clipboard-history-client-sdk", version = "0", path = "../client-sdk", features = ["error-stack", "ui"] }
rustix = { version = "0.38.34", features = ["stdio"] }
thiserror = "1.0.63"
tracy-client = { version = "0.17.3", optional = true }
tui-textarea = "0.6.1"

[features]
trace = ["dep:tracy-client"]

[[bin]]
name = "ringboard-tui"
path = "src/main.rs"
