[package]
name = "clipboard-history-egui"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Ringboard egui client application."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "egui"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
eframe = "0.27.2"
ringboard-sdk = { package = "clipboard-history-client-sdk", version = "0", path = "../client-sdk" }

[[bin]]
name = "ringboard-egui"
path = "src/main.rs"
