[package]
name = "clipboard-history-egui"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Ringboard egui client application."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "egui"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
eframe = { version = "0.28.1", default-features = false, features = ["glow", "wayland", "x11"] }
image = "0.25.2"
ringboard-sdk = { package = "clipboard-history-client-sdk", version = "0", path = "../client-sdk" }
rustc-hash = "2.0.0"
tracy-client = { version = "0.17.0", optional = true }

[features]
trace = ["dep:tracy-client"]

[[bin]]
name = "ringboard-egui"
path = "src/main.rs"
