[package]
name = "clipboard-history"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "CLI for interfacing with the ringboard server."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "cli"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
clap = { version = "4.4.18", features = ["derive", "wrap_help"] }
clap-num = "1.1.1"

[dev-dependencies]
supercilex-tests = { version = "0.4.4", default-features = false, features = ["clap"] }
