[package]
name = "clipboard-history"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "CLI for interfacing with the ringboard server."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "cli"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
ask = { package = "ask-cli", version = "0.3.0" }
clap = { version = "4.4.18", features = ["derive", "wrap_help"] }
clap-num = "1.1.1"
ringboard-core = { package = "clipboard-history-core", version = "0", path = "../ringboard" }
ringboard-sdk = { package = "clipboard-history-client-sdk", version = "0", path = "../client-sdk" }
error-stack = "0.4.1"
fuc_engine = "2.0.0"
rustix = { version = "0.38.30", features = ["stdio", "event"], path = "/home/asaveau/Desktop/wip/rustix" }
thiserror = "1.0.56"

[dev-dependencies]
supercilex-tests = { version = "0.4.4", default-features = false, features = ["clap"] }

[[bin]]
name = "ringboard"
path = "src/main.rs"
