[package]
name = "clipboard-history-client-sdk"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "API bindings to the ringboard server."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "sdk"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
arrayvec = "0.7.4"
image = "0.25.2"
memchr = "2.7.4"
regex = "1.10.5"
ringboard-core = { package = "clipboard-history-core", version = "0", path = "../ringboard" }
rustc-hash = "2.0.0"
rustix = { version = "0.38.34", features = ["net", "fs", "thread"] }
smallvec = "1.13.2"
thiserror = "1.0.63"

[dev-dependencies]
supercilex-tests = { version = "0.4.6", default-features = false, features = ["api"] }
