[package]
name = "clipboard-history-client-sdk"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "API bindings to the ringboard server."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "sdk"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
arrayvec = "0.7.4"
memchr = "2.7.4"
memmap2 = "0.9.4"
regex = "1.10.5"
ringboard-core = { package = "clipboard-history-core", version = "0", path = "../ringboard" }
rustix = { version = "0.38.30", features = ["net", "fs"] }
thiserror = "1.0.58"

[dev-dependencies]
supercilex-tests = { version = "0.4.4", default-features = false, features = ["api"] }
