[package]
name = "clipboard-history-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "The ringboard server."
repository.workspace = true
keywords = ["ringboard", "clipboard", "tools", "server"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
arrayvec = "0.7.4"
bitcode = { version = "0.6.0", features = ["arrayvec"] }
env_logger = "0.11.3"
error-stack = "0.4.1"
io-uring = { version = "0.6.2", path = "/home/asaveau/Desktop/wip/io-uring" }
libc = "0.2.153"
log = { version = "0.4.21", features = ["release_max_level_info"] }
ringboard-core = { package = "clipboard-history-core", version = "0", path = "../ringboard" }
rustix = { version = "0.38.30", features = ["fs", "process", "net"] }
thiserror = "1.0.58"

[[bin]]
name = "ringboard-server"
path = "src/main.rs"
